# Generated by Django 3.2.6 on 2021-08-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poortwitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
